const STATUS = {
    PAID: "PAID",
    PENDING: "PENDING"
}

const FREQUENCY  = {
    MONTHLY: "MONTHLY",
    YEARLY: "YEARLY"
}

const ACCOUNT_TYPE = {
    PRIMARY: "PRIMARY",
    SECONDARY: "SECONDARY"
} 


const METHODS = {
    CASH: "CASH",
    CARD: "CARD"
}

const EXPENSES_TYPE = {
    FOOD: "FOOD",
    TRANSPORTATION: "TRANSPORTATION",
    GIFT: "GIFT",
    ESSENTIAL: "ESSENTIAL",
    ACTIVITY: "ACTIVITY",
    BILL: "BILL",
    OTHER: "OTHER"
}

module.exports = {
    STATUS,
    FREQUENCY,
    ACCOUNT_TYPE,
    EXPENSES_TYPE,
    METHODS
}